name: Merge Pull Requests

# When someone comment "/deploy" on anyone PR,
# this workflow will be triggered and run.
on:
  pull_request:
  push:
    branches:
      - develop
      - staging
      - staging2
      - master
      - trying

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
jobs:
#job for checkout the ckb
  checkout: 
    name: ckb-checkout  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux-runner, mac-runner,win-runner]
        include:
          - os: Linux-runner
            script_run: make build    
          - os:  mac-runner
            script_run: export PATH="/Users/administrator/.cargo/bin:$PATH" && make build 
          - os: win-runner
            script_run: devtools/windows/make prod 
    steps:
    - name: Set env
      run: echo "CARGO_TARGET_DIR=$(echo $HOME/target)" >> $GITHUB_ENV
    - uses: actions/checkout@v2
      with:
        submodules: false
        fetch-depth: 2
        ref: ${{ github.event.pull_request.head.sha }}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - run: ${{ matrix.script_run }}

  UnitTest: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux-runner, mac-runner,win-runner]
        include:
          - os: Linux-runner
            script_run: make test    
          - os:  mac-runner
            script_run: export PATH="/Users/administrator/.cargo/bin:$PATH" && make build 
          - os: win-runner
            script_run: devtools/windows/make test 
            env:
              CI: true
              ImageOS: 'windows-2019'
              BUILD_BUILDID: ${{ github.sha }} 
    needs: checkout
    steps:
    - name: Set env
      run: echo "CARGO_TARGET_DIR=$(echo $HOME/target)" >> $GITHUB_ENV
    - name: UnitTest
      run: ${{ matrix.script_run }} 

  Linters: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        -  Linux-runner
        -  mac-runner
    needs: UnitTest
    steps:
    - name: Set env
      run: echo "CARGO_TARGET_DIR=$(echo $HOME/target)" >> $GITHUB_ENV
    - name: Linters
      run: |
         if [ ${{ runner.os }} == "macOS" ]; then
         export PATH="/Users/administrator/.cargo/bin:$PATH"
         fi
         cargo fmt --version ||  rustup component add rustfmt
         cargo clippy --version ||  rustup component add clippy
         make fmt
         make clippy
         git diff --exit-code Cargo.lock
  Latest_Linters:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        -  Linux-runner
        -  mac-runner
    needs: Linters 
    continue-on-error: true
    steps:
    - name: Set env
      run: echo "CARGO_TARGET_DIR=$(echo $HOME/target)" >> $GITHUB_ENV
    - name: Latest_Linters
      run: |
        if [ ${{ runner.os }} == "macOS" ]; then
        export PATH="/Users/administrator/.cargo/bin:$PATH"
        rustup component add rustfmt-preview
        rustup component add clippy-preview
        fi
        if [ ${{ runner.os }} == "Linux" ]; then
        rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
        rustup component add clippy --toolchain stable-x86_64-unknown-linux-gnu
        fi
        mv rust-toolchain rust-toolchain.bak
        echo "stable" > rust-toolchain
        make fmt
        make clippy
        mv rust-toolchain.bak rust-toolchain
  Quick_Check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        -  Linux-runner
        -  mac-runner
    needs: Latest_Linters
    steps:
    - name: Set env
      run: echo "CARGO_TARGET_DIR=$(echo $HOME/target)" >> $GITHUB_ENV  
    - name: Quick_Check
      run: |
        pwd
        if [ ${{ runner.os }} == "macOS" ]; then
        export PATH="/Users/administrator/.cargo/bin:$PATH"
        fi
        make check-cargotoml
        make check-whitespaces
        make check-dirty-rpc-doc
        make check-dirty-hashes-toml
        devtools/ci/check-cyclic-dependencies.py 
  Cyclic_dev_dependencies:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        -  Linux-runner
        -  mac-runner
    needs: Quick_Check  
    continue-on-error: true
    steps:
    - name: Set env
      run: echo "CARGO_TARGET_DIR=$(echo $HOME/target)" >> $GITHUB_ENV
    - name: Cyclic_dev_dependencies
      run: |
        if [ ${{ runner.os }} == "macOS" ]; then
        export PATH="/Users/administrator/.cargo/bin:$PATH"
        fi
        devtools/ci/check-cyclic-dependencies.py --dev
  Security_Audit_Licenses:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        -  Linux-runner
        -  mac-runner
    needs: Cyclic_dev_dependencies
    continue-on-error: true
    steps: 
    - name: Set env
      run: echo "CARGO_TARGET_DIR=$(echo $HOME/target)" >> $GITHUB_ENV 
    - name: Security Audit & Licenses
      run: |
        if [ ${{ runner.os }} == "macOS" ]; then
        export PATH="/Users/administrator/.cargo/bin:$PATH"
        fi
        cargo deny --version || cargo install cargo-deny --locked
        make security-audit
        make check-crates
        make check-licenses
  WASM_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        -  Linux-runner
        -  mac-runner
    needs: Security_Audit_Licenses
    steps: 
    - name: Set env
      run: echo "CARGO_TARGET_DIR=$(echo $HOME/target)" >> $GITHUB_ENV
    - name: WASM build
      run: |
        if [ ${{ runner.os }} == "macOS" ]; then
        export PATH="/Users/administrator/.cargo/bin:$PATH"
        fi
        export PATH=/usr/lib/llvm-8/bin:$PATH
        rustup target add wasm32-unknown-unknown
        make wasm-build-test
  Benchmarks_Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        -  Linux-runner
        -  mac-runner
    needs: WASM_build
    steps: 
    - name: Set env
      run: echo "CARGO_TARGET_DIR=$(echo $HOME/target)" >> $GITHUB_ENV
    - name: Benchmarks_Test
      run: |
        make bench-test
  Integration_Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux-runner, mac-runner,win-runner]
        include:
          - os: Linux-runner
            script_run: RUST_BACKTRACE=1 RUST_LOG=${INTEGRATION_RUST_LOG} test/run.sh --release -- --bin $CARGO_TARGET_DIR/release/ckb ${CKB_TEST_ARGS}  
          - os:  mac-runner
            script_run: export PATH="/Users/administrator/.cargo/bin:$PATH" && RUST_BACKTRACE=1 RUST_LOG=${INTEGRATION_RUST_LOG} test/run.sh --release -- --bin $CARGO_TARGET_DIR/release/ckb ${CKB_TEST_ARGS}
          - os: win-runner
            script_run: devtools/windows/make CKB_TEST_SEC_COEFFICIENT=5 CKB_TEST_ARGS="-c 4 --no-report" integration 
            CI: true
            SENTRY_DSN: 'https://15373165fbf2439b99ba46684dfbcb12@sentry.nervos.org/7'
            LOGBAK_USER: $(LOGBAK_USER)
            LOGBAK_PASSWORD: $(LOGBAK_PASSWORD)
            LOGBAK_SERVER: $(LOGBAK_SERVER)
    needs: Benchmarks_Test
    steps: 
    - name: Set env
      run: echo "CARGO_TARGET_DIR=$(echo $HOME/target)" >> $GITHUB_ENV
    - name: Integration_Test
      run: ${{ matrix.script_run }}
  ci-success:
    name: ci
    if: ${{ success() }}
    needs:
      - Test
      - Linters
      - Quick_Check
      - Security_Audit_Licenses
      - WASM_build
      - Benchmarks_Test
      - Integration_Test
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0

        

 


