name: CI
on:
  # Only run when merging to master, or open/synchronize/reopen a PR.
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: echo "1234"

  ci-success:
    name: ci
    if: ${{ success() }}
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
